name: PyPI Trusted Publisher

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build sdist + wheel
        run: |
          python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest

    # Optional but strongly recommended:
    # create an Environment named "pypi" in GitHub settings (can add protection rules).
    environment:
      name: pypi
      url: https://pypi.org/project/asrle/

    permissions:
      contents: read
      id-token: write  # REQUIRED for Trusted Publishing (OIDC) :contentReference[oaicite:4]{index=4}

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist